### ISSUE TITLE
Things to sort Monday - Figures and tables

### ISSUE THREAD

**Issue by bevans249** [bevans249/modelling_covid_impact_RI#11]
- [x] Legends: Should I define DTP3, LIC etc. in the figure legend or is that kind of thing just accepted? _Yes, should be defined in each. Also for table add the detail on bold_
- [x] Table formatting: Has to be as word format. Is this okay or too small font/ not enough space around the text?
- [x] Colour scheme: Is Wes Anderson acceptable?
- [x] Titles: What titles for figures and table?
- [x] Word count: about ~300-400 words in the titles, tables, legends of tables/figures. Is that okay on top of ~1100 words?

**Comment by thibautjombart** [comment]
* Legends: define the term the first time they appear in a legend.
* Table looks fine
* Wes Anderson rules
* Titles: will make suggestions / discuss with you
* Words cound: I'll look for cuts during the last edit but probably not a big issue for now.
