### ISSUE TITLE
Gavi stuff

### ISSUE THREAD

**Issue by bevans249** [bevans249/modelling_covid_impact_RI#4]
Do we want to include any Gavi-related things in the paper? In the current code there are t-test by Gavi status (full range of eligibility statuses, and binary version).
However, it doesn't add much (since nothing interesting across groups) and is the least replicable part (since the list of country eligibility statuses either takes a lot of effort to track down publicly). 
I'll delete all sections of code if not particularly useful/ interesting.

**Comment by thibautjombart** [comment]
Happy to leave this out.
