### ISSUE TITLE
home directory issues

### ISSUE THREAD

**Issue by bevans249** [bevans249/modelling_covid_impact_RI#5]
Sooo... on R studio I have home::home taking my to my R files saved on my desktop (because I am a technology n00b). This causes some issues when working on a GitHub file. I tried setting working directory to the GitHub folder but it didn't fix itself and still seems confused to the old folder. It gives me some kind of dev.off() error and says unable to open file.

**Comment by thibautjombart** [comment]
This is very bizarre, but also, I admittedly don't quite understand what you mean :) Shall we troubleshoot this one on zoom?
