### ISSUE TITLE
UN WPP data import issues

### ISSUE THREAD

**Issue by bevans249** [bevans249/modelling_covid_impact_RI#6]
https://github.com/bevans249/modelling_covid_impact_RI/blob/582e9d0741f045162380d0d16cc628f86d9e1bb0/report_sources/analyses_gavi_removed.Rmd#L84

Having issues with UN WPP data because it's a super ugly file that has a massive header. I think best practice would be to allow people to import the raw file from UN WPP then clean the crap to calculate the medium estimates surviving infants populations by births - infant mortality, but I need this file to import to do that. 

Might need to discuss this on Zoom.

**Comment by thibautjombart** [comment]
Sure, let's make a list of things to chat about and catch up on zoom.
